### ISSUE TITLE
~25-30 % of time spend in AliPhysicsSelection::EvaluateTriggerLogic when analyzing LHC15o AODs

### ISSUE THREAD

**Issue by cbourjau** [alisw/AliPhysics#1507]
Hello,

I noticed today that my analysis spends a lot of time in AliPhysicsSelection::EvaluateTriggerLogic. I am running on the LHC15o AODs and have the AliPhysicsSelection task added. 
To be more precise, the vast majority of the time is spend in TFormula::Compile(). Now I don't know exactly what this piece of code is doing, but that surely sounds like a lot of CPU power to me. Even if the logic were to be unaltered, I think we can cut the time here in half. Namely, TFormuar::Compile is called in the constructor, but its later called again to check the result [(link)](https://github.com/alisw/AliPhysics/blob/da28d5c678c8d50e1381b23ad4b13b74c297162f/OADB/AliPhysicsSelection.cxx#L302-L305)

As far as I can see (on first glance), the second call to Compile only returns not 0 if ndim ==0 [(link)](https://root.cern.ch/doc/master/TFormula__v5_8cxx_source.html#l02289). So one could just call GetNdims() directly, saving the costly compilation.

Might this be worth a consideration?

Attached is a "FlameGraph" showing the issue

[8224.pdf](https://github.com/alisw/AliPhysics/files/1098206/8224.pdf)

**Comment by ekryshen** [comment]
Hi Christian,

Thanks for reporting this issue. I am not sure if this piece of code can be easily optimized because it is called for every event and the logic of the formula may be different event by event. This part was actually introduced by Michele/Jan Fiete. I will have a look but probably not earlier than in two weeks from now.

Cheers,
Evgeny

**Comment by cbourjau** [comment]
Hi Evgeny,

I created a PR fixing this issue to the best of my knowledge. It certainly needs an expert's sets of eyes to take a look: #1537

Cheers,
Christian
