### ISSUE TITLE
Compile EMCal with -Wall

### ISSUE THREAD

**Issue by aaniin** [alisw/AliPhysics#2193]
Hello EMCal!

With master from today 3pm CERN time:
http://www.physi.uni-heidelberg.de/~hbeck/EMCal-5.txt

@raymondEhlers There are more warnings in AliEmcalCorrectionTask
@mfasDa also some warning in AliEmcalCellMonitorTask

I hope this is the last round! 

Cheers,
Hans

**Comment by mfasDa** [comment]
Hi @aaniin ,

OK, I will have a look!

Since we are already at the step of cleaning the warnings could someone please look at this (in AliRoot):

/home/markus/alice/sw/ubuntu1404_x86-64/AliRoot/ali-work-1/include/AliESD.h: In member function 'void AliESD::GetDiamondCovXY(Float_t*) const':
/home/markus/alice/sw/ubuntu1404_x86-64/AliRoot/ali-work-1/include/AliESD.h:161:5: error: this 'for' clause does not guard... [-Werror=misleading-indentation]
     for(Int_t i=0;i<3;i++) cov[i]=fDiamondCovXY[i]; return;
     ^~~
/home/markus/alice/sw/ubuntu1404_x86-64/AliRoot/ali-work-1/include/AliESD.h:161:53: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'for'
     for(Int_t i=0;i<3;i++) cov[i]=fDiamondCovXY[i]; return;

Once fixed we can increase the level for EMCAL to Wall and force warning-free code.

Cheers 

Markus

**Comment by raymondEhlers** [comment]
Hi @aaniin,

Thanks for your continued work on all of this! I'll look into resolving the warnings related to the EMCal Correction Framework.

However, I'm also a bit concerned about some of the -Weffc++ warnings that I see in the log. In particular, I'm seeing some of those warnings in yaml-cpp (in PWG/Tools/yaml-cpp). We embedded yaml-cpp into AliPhysics to support the EMCal Corrections Framework (and will likely use it more broadly soon). With that in mind, I'm not super thrilled by the prospect of having to maintain our own patches on more-or-less external software just to resolve those warnings. I guess we could propose some changes upstream (and admittedly we are behind the master right now and so perhaps some are fixed - I was waiting to update it until their next release), but it seems like we may be adding to our workload without much benefit (even if the current changes that I see aren't terribly large). Have you thought about how to handle this?

Best,
Raymond

**Comment by mfasDa** [comment]
Hi @aaniin, Hi @raymondEhlers ,

I just opened pull request #2194 where the warnings/errors you report are fixed. I have tested under Wall && Werror under gcc 6.2 and apart from the issue coming from the AliESD the code compiles now under Wall. 

@raymondEhlers: The errors from YAML are all Weffc warnings which were treated in my case still as warnings. Probably Wall=noWeffc is set in the cmake file of yaml-cpp.

Cheers

Markus

**Comment by aaniin** [comment]
Hello @mfasDa, @raymondEhlers ,

I can confirm, -Weffc++ are still warnings, they don't get promoted to errors, also in my case.

Thanks for this huge effort! 

Cheers,
Hans

**Comment by aaniin** [comment]
See https://github.com/alisw/AliRoot/pull/362

**Comment by raymondEhlers** [comment]
Hi @mfasDa, @aaniin,

Thanks for the explanation about Weffc++ - I didn't catch that it won't be treated as an error.

@mfasDa Thanks for fixing all of the warnings!

Best,
Raymond

**Comment by aaniin** [comment]
Hello @mfasDa , @raymondEhlers ,

I can confirm successful compilation on Ubuntu 16.04, gcc  5.4.0 (standard gcc on Ubuntu 16.04).

On macOS Sierra with clang 8.1.0 I get 
```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMaker.cxx:195:46: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
    std::array<std::string, 3> patchtypes = {"Online", "Offline", "Recalc"};
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                             {                            }
1 error generated.
```
I would think that there are braces, I mean I see them! Weird.

**Comment by aaniin** [comment]
https://stackoverflow.com/questions/31555584/why-is-clang-warning-suggest-braces-around-initialization-of-subobject-wmis
Resolved by gcc by no longer including -Wmissing-braces in -Wall since gcc 4.8 
https://bugs.llvm.org/show_bug.cgi?id=21629

**Comment by aaniin** [comment]
Dear @pzhristov ,

Here's the attempt to compile AliPhysics with -Wall. 

We succeed with gcc but clang has an annoying warning -Wmissing-braces included in -Wall which is not necessarily helpful. What do you think? Should one adapt the code to make all compilers happy with -Wall or restrict oneself to a subset of warnings? 

Cheers,
Hans

**Comment by aaniin** [comment]
Some more: https://stackoverflow.com/questions/16985687/brace-elision-in-stdarray-initialization
looks like one really misses braces? If somebody understands this better..

**Comment by mfasDa** [comment]
Hi @aaniin ,

I have also cross checked this, and the compiler is right (as expected): As std::array itself is a struct, we do 2 initializations in one step: The initialization of the struct (outer brackets) and the (c++11) *list*-initialization of the member array (inner brackets). So with c++11 list-initialization actually 2 brackets are needed.

I will fix this immediately, however I am not sure there are not more cases like this.

Best Regards

Markus

**Comment by aaniin** [comment]
@mfasDa two more of the same type

```c++
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx:93:60: error: suggest
 braces around initialization of subobject [-Werror,-Wmissing-braces]
  const std::array<const TString, 3>  kTriggerTypeNames = {"EJE", "EGA", "EL0"},
                                                           ^~~~~~~~~~~~~~~~~~~
                                                           {                  }
/Users/hbeck/alice/alibuild/sw/SOURCES/AliPhysics/0/0/PWG/EMCAL/EMCALtrigger/AliEmcalTriggerMakerTask.cxx:94:54: error: suggest
 braces around initialization of subobject [-Werror,-Wmissing-braces]
                                      kPatchTypes = {"Online", "Offline", "Recalc"};
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                     {                            }
2 errors generated.
```

**Comment by aaniin** [comment]
Dear @raymondEhlers , dear @mfasDa ,

Congrats on this achievement! Clearly, EMCal gives a shining example of clean code. 

I hope we can further discuss whether&how to add -Wall (or some other warnings) on the ana-op list or also the Computing Board. EMCal gives a great real life example how it can be done, this experience here is super valuable input for any such decision. 

Cheers,
Hans
