### ISSUE TITLE
PWGCF - AliFemtoModelWeightGenerator always prints warning to stdout

### ISSUE THREAD

**Issue by akubera** [alisw/AliPhysics#376]
I'm currently having an issue where I get the weight for a pair (using AliFemtoModelWeightGeneratorBasic) before checking any properties of the pair, and would like to skip further processing if the weight is zero. The code currently prints the warning
`weight generator zero tPt || tMt || tM || tPt 0 0`
every time a massless/0-momentum particle is passed through (0 is then returned by the generator).

[Link To Code](https://github.com/alisw/AliPhysics/blob/f398f8c/PWGCF/FEMTOSCOPY/AliFemto/AliFemtoModelWeightGeneratorBasic.cxx#L90)

I propose we add a flag to the WeightGenerators to enable hiding this warning (though keeping it as default) for those of us who want to use it as a feature and do not want to produce large log files.

Alternatively:
1) we could remove the cout completely; 
2) instead of writing to cout we could officially make it a warning by using AliWarning.

**Comment by dberzano** [comment]
Hi @akubera, please open an issue on JIRA and assign it to the proper person (we don't use GitHub issues for now).
